### ISSUE TITLE
Support for fetchPypi

### ISSUE THREAD

**Issue by pingiun** [samueldr/nix-universal-prefetch#2]
fetchPypi is not autodetected, could it be added?

**Comment by samueldr** [comment]
While it's not detected, it's working fine. I'll be thinking about a way to list fetchers into recursable attrsets.

The way this was implemented, anything that is accessible from `pkgs` is accessible, even if not listed. You can use `pythonPackages.fetchPypi` as long as you know its parameter names, here `pname` and `version`:

```
nix-universal-prefetch pythonPackages.fetchPypi \
    --pname home-assistant-frontend \
    --version 20200519.1
149v56q5anzdfxf0dw1h39vdmcigx732a7abqjfb0xny5484iq8w
```

(From a random fetchPypi user in Nixpkgs.)

Sorry I missed this issue, I wasn't subscribed to my own repo, it seems :/...
